"""Enums for HCC."""
from enum import Enum


class ElemId(Enum):
    """Enum representing the unique id of an element."""
    NONE = "none"
    SPACE = "space"
    FLOOR = "floor"
    WALL = "wall"
    INVISIBLE_WALL = "invisible_wall"
    MYSTERY_WALL = "mystery_wall"
    POP_UP_WALL = "pop_up_wall"
    PANEL = "panel"
    WATER = "water"
    FIRE = "fire"
    FORCE = "force"
    ICE = "ice"
    DIRT = "dirt"
    GRAVEL = "gravel"
    SOCKET = "socket"
    EXIT = "exit"
    DOOR = "door"
    THIEF = "thief"
    TOGGLE_WALL = "toggle_wall"
    TELEPORT = "teleport"
    TRAP = "trap"
    HINT = "hint"
    CLONER = "cloner"
    CHIP = "chip"
    BUTTON = "button"
    BOMB = "bomb"
    KEY = "key"
    FLIPPERS = "flippers"
    FIRE_BOOTS = "fire_boots"
    SKATES = "skates"
    SUCTION_BOOTS = "suction_boots"
    BLOCK = "block"
    ANT = "ant"
    FIREBALL = "fireball"
    BALL = "ball"
    TANK = "tank"
    GLIDER = "glider"
    TEETH = "teeth"
    WALKER = "walker"
    BLOB = "blob"
    PARAMECIUM = "paramecium"
    PLAYER = "player"


class Color(Enum):
    """Enum representing the unique color of an element."""
    NONE = "none"
    RED = "red"
    BLUE = "blue"
    YELLOW = "yellow"
    GREEN = "green"
    BROWN = "brown"


class Direction(Enum):
    """Enum representing the unique direction of an element."""
    NONE = "none"
    N = "n"
    E = "e"
    S = "s"
    W = "w"


class Rule(Enum):
    """Enum representing the unique rule of an element."""
    NONE = "none"
    BECOMES_WALL = "becomes_wall"
    BECOMES_FLOOR = "becomes_floor"
    PERSISTS = "persists"
    OPEN = "open"
    SHUT = "shut"
    TOGGLE = "toggle"
    HOLD_ONE = "hold_one"
    HOLD_ALL = "hold_all"
    SINGLE_USE = "single_use"
    UNLIMITED_USE = "unlimited_use"


class Arg(Enum):
    """Enum representing the argument key of an element."""
    NONE = "none"
    ELEMID = "elemid"
    DIRECTION = "direction"
    COLOR = "color"
    RULE = "rule"
    COUNT = "count"
    CHANNEL = "channel"
    INDEX = "index"


class Layer(Enum):
    """Enum representing layers of a cell."""
    NONE = "none"
    TERRAIN = "terrain"
    BUTTON = "button"
    PICKUP = "pickup"
    MOB = "mob"
    N = "n"
    E = "e"
    S = "s"
    W = "w"
